import SwiftUI

struct AboutView: View {
    var body: some View {
        VStack(spacing: 20) {
            Spacer()
            
            Image(nsImage: NSApp.applicationIconImage)
                .resizable()
                .frame(width: 80, height: 80)
            
            VStack {
                Text("NoDoze")
                    .font(.largeTitle)
                    .fontWeight(.bold)
                Text("A tiny macOS menu-bar utility that intelligently keeps your Mac awake on demand.")
                    .multilineTextAlignment(.center)
                    .foregroundColor(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }
            
            Divider()
            
            VStack(alignment: .leading, spacing: 15) {
                Text("Purpose")
                    .font(.headline)
                Text("NoDoze was born out of a specific frustration: keep-awake utilities that are too aggressive, draining the battery even when the lid is closed. This app is smart enough to stand down when all screens are off, letting your Mac sleep when it should, while providing robust keep-awake functionality when you need it.")
                    .foregroundColor(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
                
                Text("AI-Powered Development")
                    .font(.headline)
                Text("This app was built as an experiment in 'Vibe Coding'. Every file, from the code to the icon to this text, was generated by an AI under human direction. It's an exploration of what's possible in modern software development.")
                    .foregroundColor(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }
            
            Spacer()
        }
        .padding(30)
        .frame(width: 400)
    }
}

struct AboutView_Previews: PreviewProvider {
    static var previews: some View {
        AboutView()
    }
} 